### ISSUE TITLE
Linking fails (missing lgcc and lgcc_eh)

### ISSUE THREAD

**Issue by aarbakk** [sba1/adtools#10]
When compiling & linking with gcc, I get the following error messages:
ld: cannot find -lgcc
ld: cannot find -lgcc_eh

This fails:
gcc Hello.c -o Hello

Compiling without linking works:
gcc -c Hello.c

...but fails when linking:
gcc -o Hello Hello.o

**Comment by sba1** [comment]
Am 2016-01-10 13:32, schrieb aarbakk:
> When compiling & linking with gcc, I get the following error messages:
> ld: cannot find -lgcc
> ld: cannot find -lgcc_eh
> 
> This fails:
> gcc Helloc -o Hello
> 
> Compiling without linking works:
> gcc -c Helloc
> 
> but fails when linking:
> gcc -o Hello Helloo

For the time beging, please use ```-Wl,-verbose``` to see which paths 
are looked for and then move the libgcc.a and relates files accordingly.

**Comment by aarbakk** [comment]
This solved the issue, thanks!
