### ISSUE TITLE
gcc10 and gthread

### ISSUE THREAD

**Issue by afxgroup** [sba1/adtools#100]
Finally it seems i've found the cuplrit for some error i have on destructors.
OS4 is showing me an error that __gthread_mutex_destroy is not resolved in libstdc++.so

And indeed if i use nm to test it it is undefined

```
root@amigabuild2:~# nm /opt/adtools10/native-build/root-cross/ppc-amigaos/lib/clib2/libstdc++.so | grep __gthread_mutex_destroy
         U __gthread_mutex_destroy
```

it happens because is defined as 

```
int
__gthread_mutex_destroy (__gthread_mutex_t *__mutex UNUSED)
{
  return 0;
}
```

Why it is unused?

**Comment by raziel-** [comment]
@afxgroup 

Why did you close it again?
Was it already fixed?

**Comment by afxgroup** [comment]
No but is not related by the UNUSED. because that UNUSED is related to argument (i didn't saw it correctly..). The problem is elsewhere. I've seen that the two objects that should be linked with libgcc are in the lib folder. I'm trying to recompile everything to understand where is the problem. However it is the problem. That functions are not present in compiled libgcc when using shared objects. Most probably with static objects you don't have this problem because they are linked using -athread flag.

**Comment by raziel-** [comment]
@afxgroup 

Thank you for the explanation.

I'm following closely everything that has to do with potential bugs/fixes in the shared objects.
Still hoping for a fix to the crash in scummvm.

**Comment by afxgroup** [comment]
Which kind of crash you have?

**Comment by raziel-** [comment]
Basically it will crash on starting scummvm.
I dont get any window or screen opened, so it seems to be pretty early on. Maybe even as early as accessing libstdc++.so.

I can provide a crash log, if you are interested, but probably not on this closed issue (and not right now, still at work)?

**Comment by afxgroup** [comment]
can you give me the scummvm version that cause the problem? Maybe also the source code (a link somewhere)

**Comment by raziel-** [comment]
Of course.
Not before the weekend though.

I'll PM you on amigans

Thank you:-)

**Comment by afxgroup** [comment]
drop me a mail please. not a PM on amigans otherwise i'll never see it.. thanks

**Comment by raziel-** [comment]
I don't have it...and dont want you to reveal it here, hence the pm(?)

**Comment by afxgroup** [comment]
ok

**Comment by afxgroup** [comment]
I've (partially) fixed the issue.

```
root@amigabuild2:/opt/adtools10# nm /usr/lib/gcc/ppc-amigaos/10.1.0/clib2/libgcc.so | grep __gthread
10008190 T __gthread_active_p
100082fc t __gthread_close_timer
100095ac T __gthread_cond_broadcast
10009b08 T __gthread_cond_destroy
100094d4 T __gthread_cond_init
100094f0 T __gthread_cond_signal
10009774 T __gthread_cond_timedwait
1000968c T __gthread_cond_wait
10008e78 t __gthread_cond_wait_prepare
10008f88 T __gthread_create
100092bc T __gthread_detach
100083c8 t __gthread_entry
10009338 T __gthread_equal
10008954 T __gthread_getspecific
100091c0 T __gthread_join
100086ec T __gthread_key_create
100088b8 T __gthread_key_delete
10008ba0 T __gthread_mutex_destroy
10008bac T __gthread_mutex_init
10008c28 T __gthread_mutex_lock
10008d08 T __gthread_mutex_trylock
10008df8 T __gthread_mutex_unlock
1000853c t __gthread_new_threadentry
10008198 T __gthread_once
10008f80 T __gthread_recursive_mutex_destroy
10008f38 T __gthread_recursive_mutex_init
10008f74 T __gthread_recursive_mutex_lock
10008f78 T __gthread_recursive_mutex_trylock
10008f7c T __gthread_recursive_mutex_unlock
1000934c T __gthread_self
10008a64 T __gthread_setspecific
10009454 T __gthread_yield
```

Partially because i've added:

`LIB2ADD = $(srcdir)/gthr-amigaos-native.c
`

to gcc/repo/libgcc/config/rs6000/t-amigaos

But this means that in libgcc is always used native threading and is not possible to select it. But this should avoid to use "athread" flag

**Comment by afxgroup** [comment]
i have also a problem on destructors here:

gcc/repo/libstdc++-v3/libsupc++/eh_globals.cc

```
struct __eh_globals_init
{
  __gthread_key_t       _M_key;
  bool                  _M_init;

  __eh_globals_init() : _M_init(false)
  {
    if (__gthread_active_p())
      _M_init = __gthread_key_create(&_M_key, eh_globals_dtor) == 0;
  }

  ~__eh_globals_init()
  {
#ifndef __amigaos4__
    if (_M_init)
      __gthread_key_delete(_M_key);
#endif
    _M_init = false;
  }
};
```

This fix the problem at least on my setup. Now the stdc++.so seems to working correctly. I've read googling around that key delete should not be called in destructors.. and indeed it fix the problem at leas on os4

**Comment by raziel-** [comment]
@afxgroup

You have mail, thank you for looking
