### ISSUE TITLE
Test compilation fails after installing packages

### ISSUE THREAD

**Issue by Hypexed** [sba1/adtools#15]
Hello. I installed the packages on Linux Mint 64. I also installed the extra libs needed to build it. Then tried to compile the test suite by a CD into the folder and a make. I got this back. Perhaps some extra dependencies need to be added in. Lintian gave a few errors on the packages also.

`ppc-amigaos-g++ -v -c test-exceptions.cpp -o test-exceptions.o  -ggdb
Using built-in specs.
COLLECT_GCC=ppc-amigaos-g++
Target: ppc-amigaos
Configured with: patched/configure --target=ppc-amigaos --prefix=/usr --libexec=/usr/lib --with-bugurl=http://sf.net/p/adtools --with-pkgversion='adtools build ' --enable-languages=c,c++ --enable-haifa --enable-sjlj-exceptions --disable-libstdcxx-pch --disable-tls --disable-nls
Thread model: single
gcc version 4.9.2 (adtools build ) 
COLLECT_GCC_OPTIONS='-v' '-c' '-o' 'test-exceptions.o' '-ggdb'
 /usr/lib/gcc/ppc-amigaos/4.9.2/cc1plus -quiet -v -mcrt=newlib -isystem /usr/ppc-amigaos/SDK/newlib/include -isystem /usr/ppc-amigaos/SDK/local/newlib/include -isystem /usr/ppc-amigaos/SDK/include/include_h -isystem /usr/ppc-amigaos/SDK/include/netinclude -isystem /usr/ppc-amigaos/SDK/local/common/include test-exceptions.cpp -quiet -dumpbase test-exceptions.cpp -auxbase-strip test-exceptions.o -ggdb -version -o /tmp/ccSayMfQ.s
/usr/lib/gcc/ppc-amigaos/4.9.2/cc1plus: error while loading shared libraries: libmpc.so.2: cannot open shared object file: No such file or directory
makefile:7: recipe for target 'test-exceptions.o' failed
make: *** [test-exceptions.o] Error 1
`

**Comment by sba1** [comment]
I added the libmpc dependency manually now. This problem should be fixed now.

**Comment by sba1** [comment]
Tested here and it works.

**Comment by Hypexed** [comment]
Okay thanks. :-)
