### ISSUE TITLE
Feature request - Optional relocation of "root-cross" toolchain to system-wide

### ISSUE THREAD

**Issue by Belxjander** [sba1/adtools#18]
I'm well aware this would require a path that is assigned to ownership by the user actually performing the build operation.

"mkdir -p $(target_path)" as root followed by chown and chgrp execution.

Would this be possible as an optional script for anyone to use non-debian/redhat hosts as additnal distcc nodes with a native compiler built for the master amigaos machine for anyone who has multiple machines to make a build cluster?

**Comment by sba1** [comment]
This should already be possible. Use the CROSS_PREFIX macro. E.g. ```make CROSS_PREFIX=/adtools```. Please test and report back. If it works I will document it more prominently.

**Comment by afxgroup** [comment]
I'm trying to build a linux cross compiler. I've used the **make -C native-build gcc-cross** command to compile it and all seems ok.. but how to install it? with old adtools the make install was the solution. But install rule now is not present. 

Another question is related to "root-cross" i didn't set it and i didn't compile coreutils. So my compiler will work? 

Sorry but i don't understand very well the doc. Keep in mind that i'm using Centos (so redhat) and not a debian

**Comment by sba1** [comment]
> I'm trying to build a linux cross compiler. I've used the make -C native-build gcc-cross command to compile it and all seems ok.. but how to install it? with old adtools the make install was the solution. But install rule now is not present.

Just add the root-cross/bin folder to your command path like this (as it is written in the doc)
```
$ export PATH=$PATH:$(pwd)/root-cross/bin
```
assuming that your current working directory is ```native-build```. You can then call ```ppc-amigaos-gcc```. Hope this helps.

> Another question is related to "root-cross" i didn't set it and i didn't compile coreutils. So my compiler will work?

Yes, you don't need a Amiga native coreutils in a cross compiler environment.

**Comment by sba1** [comment]
> This should already be possible. Use the CROSS_PREFIX macro. E.g. make CROSS_PREFIX=/adtools. Please test and report back. If it works I will document it more prominently.

@Belxjander Did you try this? Did it produced the expected results?

**Comment by jens-maus** [comment]
@sba1 I am constantly using CROSS_PREFIX here and it perfectly works. So IMHO this issue can be closed.

**Comment by sba1** [comment]
Thanks for confirming. I enhanced the ReadMe a bit to show the usage of CROSS_PREFIX. Will close this is issue now.

@Belxjander
Feel free to reopen it or file a new issue if it still doesn't work.
