### ISSUE TITLE
Wrong directory structure

### ISSUE THREAD

**Issue by alfkil** [sba1/adtools#20]
In the GCC 5.3.0 distribution on aminet, there are several mistakes in the directory structure, preventing c++ apps from building.

Files in

adtools-os4-20151223-268/lib/gcc/

need to be copied to

adtools-os4-20151223-268/lib/gcc/ppc-amigaos/5.3.0/newlib/lib

--
and files in

adtools-os4-20151223-268/lib/gcc/ppc-amigaos/5.3.0/lib/#?

need to be copied to

adtools-os4-20151223-268/lib/gcc/ppc-amigaos/5.3.0/newlib/lib/
--

**Comment by sba1** [comment]
I hope that this has been resolved in the meantime with commits in the past.

But I have not pushed a new release. I'm currently fighting with travis to also build the native compiler automatically. I'll add an comment to this when this is done so you can try it again.

**Comment by alfkil** [comment]
Thanks :).

**Comment by sba1** [comment]
Native build are now available in an automatic fashion. The URL is https://dl.bintray.com/sba1/adtools-native/. I haven't tested it myself though. It would be nice if you could test whether it works or if there are still some changes needed.

**Comment by sba1** [comment]
Closing now. If you think that there is still a problem, please open a new issue. Thanks.
