### ISSUE TITLE
The new SDK installer script fails if an older SDK is already been installed.

### ISSUE THREAD

**Issue by AV00** [sba1/adtools#24]
With the release of the new installer, the relative version bump induced a reinstall of the SDK (that was pinned to the first SDK). The installer script fails (thus preventing any other package change) with this error:

```
mv: inter-device move failed: `/tmp/adtools-sdk.iu3aYULGiHV/clib2' to `/usr//ppc-amigaos/SDK/clib2'; unable to remove target: Is a directory
mv: inter-device move failed: `/tmp/adtools-sdk.iu3aYULGiHV/newlib' to `/usr//ppc-amigaos/SDK/newlib'; unable to remove target: Is a directory
```

This is due to: (from the script)
 `               mv ${EXTRACTDIR}/clib2* ${EXTRACTDIR}/newlib* ${CROSS_ROOT}/ppc-amigaos/SDK
`

So we could run the script with --uninstall as a prerequisite, however this doesn't ensure the corresponding two directories will be removed, if there are any "user added" files in those two.

The other way would be yet more bash shenanigans, checking if the directories exists.

**Comment by sba1** [comment]
Generally, the user should not mess with these directory (however, I realize that the user is currently forced to so for custom "system"-wide includes).

It is possible to differentiate between an upgrade and a fresh install. We should take advantage of this.

**Comment by AV00** [comment]
> Generally, the user should not mess with these directory (however, I realize that the user is currently forced to so for custom "system"-wide includes).
> 
> It is possible to differentiate between an upgrade and a fresh install. We should take advantage of this.

I haven't messed with those directories. I guess I wasn't clear enough.

What happened is that on UPDATE of the SDK package, it downloaded the SDK and tried to overwrite the directories, but because it's using "mv", the script failed and now I'm left an incomplete configuration, thus preventing the rest of my Debian system to update.

I've tried replacing 'mv' by 'cp -Rf' and it works (leaving behind the temporary files, though). I've updated the script in my branch. Have a look and if you like, I can issue a pull request.
The other change is that I'm copying the version file to the SDK, so one can know what version he/she has installed. Useful IMHO.

**Comment by sba1** [comment]
Please issue a PR with your changes. Thanks!

**Comment by AV00** [comment]
Done.

**Comment by sba1** [comment]
I checked in your changes. Closing this...(assuming that it works)
