### ISSUE TITLE
 BFD does not support target powerpc-unknown-amigaos

### ISSUE THREAD

**Issue by afxgroup** [sba1/adtools#27]
I'm trying to compile gcc5 with cross compiling option enabled and i'm using the usual:

**make -C native-build gcc-cros**

to compile the gcc but i'm getting this error on BFD:

*** BFD does not support target powerpc-unknown-amigaos.
*** Look in bfd/config.bfd for supported targets.

What is changed in the meanwhile? i've already compiled it on another machine without any problem.

**Comment by sba1** [comment]
Looks like that you forgot to patch the binutils. See docs for usage.
