### ISSUE TITLE
libc.so

### ISSUE THREAD

**Issue by afxgroup** [sba1/adtools#29]
When i use -use-dynld flag to link a shared object i get a warning that libc.so is not found. And indeed i didn't see it into newlib folder. How can i compile shared objects? I have only the static one

**Comment by afxgroup** [comment]
no one has the same problem? We can't mix different libc.so taken from various gcc. and i suppose also the lib should be versioned.

**Comment by raziel-** [comment]
Missing the file from my SDK aswell.

Though i don't build with shared objects anymore, so can't tell

**Comment by afxgroup** [comment]
i suppose libc.so should be compiled along libc.a

**Comment by sba1** [comment]
These files are part of the SDK and not gcc. We cannot redistribute them in context of this project.

**Comment by afxgroup** [comment]
so libc.so is part of SDK and not compiled by gcc? If so, we should doesn't have any problem if compiled with different GCC version. Isn't it?

**Comment by sba1** [comment]
I think that you should able to use the libc.(a|so) supplied with the SDK. If that's not the case, we need to research why this isn't possible.

**Comment by sba1** [comment]
Assuming that it works so I close it.
