### ISSUE TITLE
HOWTO: Install within a Linux User Account for builds within the same account ?

### ISSUE THREAD

**Issue by Belxjander** [sba1/adtools#3]
I've managed to run a build of the adtools project yet have no idea how to "install" it.

And would like this to remain within a single user home directory tree created for this task.

**Comment by sba1** [comment]
More details please. How did you compile the compiler?

If you used the makefile in native-build, you will end up with root-cross directory. Add the bin directory to your path. That's all.

**Comment by sba1** [comment]
I'm closing this now. If there is still anything missing or needed, please file a new Issue.
