### ISSUE TITLE
DSI when compiling a C++ project

### ISSUE THREAD

**Issue by capehill** [sba1/adtools#30]
After reboot the same code compiled without crash. Anyway, here is the crash log in case there is something useful. I'm using the latest native release.

[Crashlog_cc1plus_2017-04-29_19-20-38.txt](https://github.com/sba1/adtools/files/966270/Crashlog_cc1plus_2017-04-29_19-20-38.txt)

**Comment by sba1** [comment]
Thanks, unfortunately, there is not much that can be inferred from the crash. Especially as it vanished after the reboot. It could be therefore some interaction with some other program (or not). If you encounter this problem again, please attach your findings here,

**Comment by capehill** [comment]
I haven't seen this problem since then. I will close it for now.
