### ISSUE TITLE
cp does not 'stat' absolute paths (unix or amiga style) 

### ISSUE THREAD

**Issue by broadblues** [sba1/adtools#32]
The cp in the latest gcc5.4 native build archive does not behave correctly when passed absolute paths for the src files.

See following session:
```
10.Programing:Projects/MultiViewer/trunk> which cp
Programing:SDK/gcc/bin/cp
10.Programing:Projects/MultiViewer/trunk> cp ram:T/usb.log ram:
cp: cannot stat `ram:/usb.log': Invalid argument
10.Programing:Projects/MultiViewer/trunk> cp /ram/T/usb.log /ram
cp: cannot stat `/ram/T/usb.log': No such file or directory
```

compared with the following session useful the builds from the previous SDK
```
10.Programing:Projects/MultiViewer/trunk> SDK:local/C/cp ram:T/usb.log ram:
10.Programing:Projects/MultiViewer/trunk> SDK:local/C/cp /ram/T/usb.log ram:
```
both successful copies

I notice the cp and presumably other coreutils commands in the package are newlib based but the older working ons are clib2 based. 

I don't think 'core utils' was ever properly ported to newlib and there is now a new clib2 build down by SSolie which should be gcc5 compatable

**Comment by sba1** [comment]
Coreutils is now built using clib2. Note that it is still at 5.2 (a newer port is available via adtools).
