### ISSUE TITLE
configuring SDL2 project fails, possibly due to new "expr" binary

### ISSUE THREAD

**Issue by capehill** [sba1/adtools#35]
Tried to configure SDL2 after installation of the latest GCC 5.4.0.

Project page: https://sourceforge.net/projects/sdl2-amigaos4/

My paths:

14.Beta41:> path

RAM Disk:
Beta41:C
Beta41:S/Shell
Beta41:S/ARexx
Beta41:System/Python/Scripts
Beta41:Utilities
Beta41:Utilities/Commodities
Beta41:System
Beta41:Prefs
Code:SDK/C
Code:adtools-os4-20170623-404/bin
Code:SDK/local/C
Temp:Qt-4.7/bin
Code:cmake-3.7.1/bin
C:

14.Beta41:> echo $PATH
/SDK/c:/gcc/bin:/SDK/local/C:/code/cmake-3.7.1/bin

8.Code:svn/sdl2-amigaos4-code/trunk> sh configure --disable-altivec --prefix=/SDK/local/newlib
configure: WARNING: unrecognized options: --disable-0
configure: error: expected an absolute directory name for --prefix: 0

WORKAROUND: I inactivated gcc:bin/expr by renaming it, and then configuring passed and project was possible to build with make (even though there were lots of other errors during configuring).

[Snoopy_Output_configure.txt](https://github.com/sba1/adtools/files/1135511/Snoopy_Output_configure.txt)

**Comment by sba1** [comment]
This is probably related to issue #32.

**Comment by capehill** [comment]
Configuring works with the latest GCC8, closing.
