### ISSUE TITLE
using stringstream causes run-time linking error

### ISSUE THREAD

**Issue by capehill** [sba1/adtools#37]
Following example works when linked statically, like "g++ sstream.cpp". If linked like "g++ sstream.cpp -use-dynld" caused binary to *crash* when started, due to an unresolved symbol.

Tested with https://dl.bintray.com/sba1/adtools-native/:adtools-os4-20170309-402.lha

```
#include <sstream>

int main(void)
{
    std::stringstream ss;
    ss << "hello";

    return 0;
}
```

**Comment by sba1** [comment]
Please have a look at issue #7, which is, I think, a related problem. In essence, make sure that the proper libstdc++.so is used.
