### ISSUE TITLE
cp (5.2.1) errors when used in makefile script

### ISSUE THREAD

**Issue by raziel-** [sba1/adtools#4]
cp ./icons/residualvm_drawer.info Games:ResidualVM.info
gcc:bin/cp: skipping file `./icons/residualvm_drawer.info', as it was replaced while being copied
gmake: **\* [amigaosdist] Error 1

It doesn't matter if the destination file exists or not.

cp 5.2.1 from the gcc 5.3.0 package errors
cp5.2.1-9 from the latest SDK 53.29 works fine

**Comment by sba1** [comment]
I think that I've fixed this one.
