### ISSUE TITLE
Linker script issue

### ISSUE THREAD

**Issue by DStastny** [sba1/adtools#41]
With the new 5.4 build I am having issue with a linker script not parsing the paths correctly.  This example fragment of script issue.

`INPUT( `"Work:BMX/Build/mod/brl.mod/appstub.mod/appstub.release.amigaos4.ppc.a")`

At link time I get request to create assign for Work:  which if I do and then look at assigns I see a new assign "Work  Work:  so there is something amiss with parsing of the quoted libs in my script.  This works with original SDK fine.

Let me know what I might provide or where I might look to assist in correcting.

Regards
Doug

**Comment by sba1** [comment]
Am 2017-12-18 19:41, schrieb DStastny:
> With the new 5.4 build I am having issue with a linker script not
> parsing the paths correctly. This example fragment of script issue.
> 
> INPUT("Work:BMX/Build/mod/brl.mod/appstub.mod/appstub.release.amigaos4.ppc.a")`
> 

> At link time I get request to create assign for Work: which if I do
> and then look at assigns I see a new assign "Work Work: so there is
> something amiss with parsing of the quoted libs in my script. This
> works with original SDK fine.


Could you try to use 
/Work/BMX/Build/mod/brl.mod/appstub.mod/appstub.release.amigaos4.ppc.a?

**Comment by DStastny** [comment]
Hi the script is generated by my compiler as part of build process so I am looking into what it will take the automation of converting the paths from Amiga to Unix.   I see the function in newlib but have been unsuccessful getting it to link correctly with a simple test application it faults for some reason.   I suspect its caused by other linking issues with my script. 

  The compiler tool chain for language is partially built in the language itself so I first need to rebuild with 4.2 before I can retest with 5.4.  Hopefully I will get some time this week.    I’m still unsure what’s changed in bintools that the linker script is not parsing correctly.

Regards
Doug


Sent from Mail for Windows 10

**Comment by DStastny** [comment]
I had a chance to modify my compilers linker script generation and all the invocation of gcc tool-chain to use UNIX style paths and it works correctly with 4.24 as well as the 5.4 build from July.   I am OK to close the issue as I have, I think the best working solution. The key is just to force path transaslation on arguments passed to GCC tool chain.   Best to document not to use Amiga Paths with the GCC Tool chain as I image trying to get it working with both all over would be mess.

I think this issue can be closed.

Sent from Mail for Windows 10

From: Douglas Stastny
Sent: Wednesday, December 20, 2017 5:25 PM
To: sba1/adtools; sba1/adtools
Subject: RE: [sba1/adtools] Linker script issue (#41)

Hi the script is generated by my compiler as part of build process so I am looking into what it will take the automation of converting the paths from Amiga to Unix.   I see the function in newlib but have been unsuccessful getting it to link correctly with a simple test application it faults for some reason.   I suspect its caused by other linking issues with my script. 

  The compiler tool chain for language is partially built in the language itself so I first need to rebuild with 4.2 before I can retest with 5.4.  Hopefully I will get some time this week.    I’m still unsure what’s changed in bintools that the linker script is not parsing correctly.

Regards
Doug


Sent from Mail for Windows 10

**Comment by sba1** [comment]
I hope that everything is solved :)
