### ISSUE TITLE
Enabling wchar_t in libstdc++

### ISSUE THREAD

**Issue by afxgroup** [sba1/adtools#42]
I'm trying to enable wchar_t compilation in libstdc++ but i don't find where the configure parameter are passed to the configure file. I've tried to add --enable-wchar_t to the main Makefile but it isn't pushed to the libstdc++ configure file.
Any tip?

**Comment by sba1** [comment]
I think it is enabled by default, but newlib doesn't support it (but AFAIK, clib2 does support it).

**Comment by sba1** [comment]
It was not enabled by default. Problem is that none of our clibs support wide characters, so the feature is automatically disabled.

I changed the compiling procedure to also compile recent versions of clib2. I enabled the stubs that were present but not active yet and implemented some of them. Wide char stuff should now compile through, but it is unlikely that it works as many functions are just stubs.

**Comment by sba1** [comment]
Closing this now as the remaining (i.e., proper support for widechars) is a task for the clib.
