### ISSUE TITLE
GCC 6.1.0: error in cstdlib include

### ISSUE THREAD

**Issue by salass00** [sba1/adtools#43]
When I try to compile C++ programs with GCC 6.1.0 I often get an error like:

/usr/local/amiga/adtools-gcc-6/ppc-amigaos/include/c++/6.1.0/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>

The problem is, I think, caused by the fact that /SDK/newlib/include is too early in the include search list (before the compiler's c++ includes) and the fact that <cstdlib> was changed to using include_next for including <stdlib.h>.

#include "..." search starts here:
#include <...> search starts here:
 /usr/local/amiga/adtools-gcc-6/ppc-amigaos/SDK/newlib/include
 /usr/local/amiga/adtools-gcc-6/ppc-amigaos/SDK/local/newlib/include
 /usr/local/amiga/adtools-gcc-6/ppc-amigaos/SDK/include/include_h
 /usr/local/amiga/adtools-gcc-6/ppc-amigaos/SDK/include/netinclude
 /usr/local/amiga/adtools-gcc-6/ppc-amigaos/SDK/local/common/include
 /usr/local/amiga/adtools-gcc-6/lib/gcc/ppc-amigaos/6.1.0/../../../../ppc-amigaos/include/c++/6.1.0
 /usr/local/amiga/adtools-gcc-6/lib/gcc/ppc-amigaos/6.1.0/../../../../ppc-amigaos/include/c++/6.1.0/ppc-amigaos
 /usr/local/amiga/adtools-gcc-6/lib/gcc/ppc-amigaos/6.1.0/../../../../ppc-amigaos/include/c++/6.1.0/backward
 /usr/local/amiga/adtools-gcc-6/lib/gcc/ppc-amigaos/6.1.0/include
 /usr/local/amiga/adtools-gcc-6/lib/gcc/ppc-amigaos/6.1.0/include-fixed
 /usr/local/amiga/adtools-gcc-6/lib/gcc/ppc-amigaos/6.1.0/../../../../ppc-amigaos/include
End of search list.

GCC 5 and earlier do not have this problem.

**Comment by sba1** [comment]
I'm looking into this. Commit gcc-mirror/gcc@6c8ced3f4f867b72a623fe2f23efa204c5786a28 replaced include with include_next.

**Comment by sba1** [comment]
And this seems to introduce the patch and lists some reason: https://gcc.gnu.org/ml/libstdc++/2016-01/msg00025.html.

We should indeed move the SDK stuff down the include search path.

**Comment by sba1** [comment]
Default path order is now different. Note that the native compiler still doesn't compile through, due to the missing unsetenv(). But this issue is fixed.
