### ISSUE TITLE
Auto generate archive for native AmigaOS4 build

### ISSUE THREAD

**Issue by ksdhans** [sba1/adtools#45]
I've managed to build the native compiler, but it's not clear how to generate the archive to be copied to my AmigaOS 4 machine. 

It would be useful if the makefile auto-generated the archive and/or the readme documented how to generate it.

**Comment by sba1** [comment]
Auto-generated native archives are available from https://dl.bintray.com/sba1/adtools-native/.

**Comment by ksdhans** [comment]
Thanks. That's certainly helpful for me (all I want is the latest GCC 5.4.0 on my AmigaOS machine). However, it would still be useful for people wanting to build their own compiler to be able to generate the archive themselves.
