### ISSUE TITLE
error: ‘to_string’ is not a member of ‘std’

### ISSUE THREAD

**Issue by kas1e** [sba1/adtools#58]
The same as with issue #57, i found another error with something not being a member of std, because of which can't compile one of c++11 programms.

I take as example that : http://www.cplusplus.com/reference/string/to_string/

`// to_string example`
`#include <iostream>   // std::cout`
`#include <string>     // std::string, std::to_string`

`int main ()`
`{`
`  std::string pi = "pi is " + std::to_string(3.1415926);`
`  std::string perfect = std::to_string(1+2+4+7+14) + " is a perfect number";`
`  std::cout << pi << '\n';`
`  std::cout << perfect << '\n';`
`  return 0;`
`}`

On cygwin and msys2 gcc it compiles fine, just like this:

$ g++ test.cpp

On our 8.2.0, i compile it like:

$ ppc-amigaos-g++ -athread=native -std=c++11 test2.cpp

And have :

`test2.cpp: In function ‘int main()’:`
`test2.cpp:7:36: error: ‘to_string’ is not a member of ‘std’`
`   std::string pi = "pi is " + std::to_string(3.1415926);`

`test2.cpp:8:30: error: ‘to_string’ is not a member of ‘std’`
`   std::string perfect = std::to_string(1+2+4+7+14) + " is a perfect number";`

**Comment by kas1e** [comment]
While with that issue, -mcrt=clib2 helps, with issue 57, it didn't. 
Also, clib2 is of no use when you port something big sadly, as there is many other places where newlib should be used instead. 

I also digin in google, and found that there was the same issue with MinGW year ago, and they made a patch for : http://tehsausage.com/mingw-to-string

Maybe it will help us as well ?

**Comment by sba1** [comment]
Am 2018-11-13 12:29, schrieb kas1e:
> While with that issue, -mcrt=clib2 helps, with issue 57, it didn't.
> Also, clib2 is of no use when you port something big sadly, as there
> is many other places where newlib should be used instead.
> 
> I also digin in google, and found that there was the same issue with
> MinGW year ago, and they made a patch for :
> http://tehsausage.com/mingw-to-string
> 
> Maybe it will help us as well ?

Newlib is lacking some functions or at least not fully C11 compliant and 
closed source. I think it is missing some wchar_t stuff, if I remember 
correctly. Some workarounds can be implemented in gcc of course, but it 
is not nice.

With clib2, we can add the missing functions as needed.

Why can't you use clib2? Is it because you want shared objects?

**Comment by kas1e** [comment]
> Why can't you use clib2? Is it because you want shared objects?

I can't say right now why exactly. Just over the years a lot of functionality in terms of posix was added to newlib. A lot of linker libs was done for newlib, which i even don't have code for even anymore. Lots of stuff was tested and compiled with newlib, so strarting the same way again with clib2, it will be veeeery long and hard, and we do not have probabaly man power to fix all issues with which was deal with in newlib previously.

**Comment by sba1** [comment]
Am 2018-11-13 12:45, schrieb kas1e:
>> Why can't you use clib2? Is it because you want shared objects?
> 
> I can't say right now why exactly. Just over the years a lot of
> functionality in terms of posix was added to newlib. A lot of linker
> libs was done for newlib, which i even don't have code for even
> anymore. Lots of stuff was tested and compiled with newlib, so
> strarting the same way again with clib2, it will be veeeery long and
> hard, and we do not have probabaly man power to fix all issues with
> which was deal with in newlib previously.

As said, fixing issues in clib2 is easy, however newlib also has a lot 
of problems wrt to the latest standard. In the long run, clib2 seems to 
be the better alternative if you ask me.

**Comment by capehill** [comment]
How about thread-safety with clib2?

**Comment by sba1** [comment]
Am 2018-11-18 17:17, schrieb capehill:
> How about thread-safety with clib2?

For clib2 there we need to use the clib2-ts variant.

**Comment by ksdhans** [comment]
I've just encountered this too. Looking at the include files, it appears that to_string() is only generated if _GLIBCXX_USE_C99_STDIO is defined. 

I tried switching to clib2, but found that #include<string> and #include <condition_variable> result i errors such as:
error: '::mbrtowc' has not been declared

Even a source file with just #include <string> fails. I'm not using wchars, and don't understand why it's including cwchar.

**Comment by ksdhans** [comment]
This problem can be fixed by adding:
#define _GLIBCXX_USE_C99_STDIO 1

to include/c++/8.1.0/ppc-amigaos/bits/c++config.h (round line 1388 is where it should be). I basically copied this from the clib2 config file. I'd send you a patch, but I can't find that file in this repository.

**Comment by raziel-** [comment]
This bit me today too, would be nice to have it supported

btw: It doesn't matter if i use -std=c++11 or -std=gnu++11, i get the same error

**Comment by ksdhans** [comment]
It would be great if this could be fixed permanently. I'd send a pull-request, but I'm not sure how to do this with the adtools project. AFAICT, adtools itself is a series of patches against GCC. So, I can't just go and edit the file here, and send a pull request because the file isn't in the repository.

**Comment by sba1** [comment]
Am 2020-04-08 09:43, schrieb ksdhans:
> It would be great if this could be fixed permanently. I'd send a
> pull-request, but I'm not sure how to do this with the adtools
> project. AFAICT, adtools itself is a series of patches against GCC.
> So, I can't just go and edit the file here, and send a pull request
> because the file isn't in the repository.

You can work as normal in the gcc checkout when checked out via gild.
Then use
  $ gild genpatch gcc XXX

To regenerate the patch set.

See https://github.com/sba1/gild and the help of gild.

**Comment by ksdhans** [comment]
@sba1 
Thanks. However, the c++config.h files are in a subdirectory of adtools/native-build/gcc-cross-build-8.3.0/. That directory created during the build process, and it looks like c++config.h is generated somehow. I haven't managed to find its source or generator code.

Any idea where to find that?

**Comment by sba1** [comment]
Am 2020-04-14 05:27, schrieb ksdhans:
> @sba1 [1]
> Thanks. However, the c++config.h files are in a subdirectory of
> adtools/native-build/gcc-cross-build-8.3.0/. That directory created
> during the build process, and it looks like c++config.h is generated
> somehow. I haven't managed to find its source or generator code.
> 
> Any idea where to find that?

See the patch 0011-Pretend-C99-compatibility.patch for an example how to 
fix such issue. The real fix would be to fix newlib of course (and to 
distribute a fixed version).

**Comment by ksdhans** [comment]
Okay, I might have found it in one of the autoconfig m4 scripts:

`    # Check for the existence in <stdio.h> of vscanf, et. al.
    AC_MSG_CHECKING([for ISO C99 support in <stdio.h> for C++11])
    AC_CACHE_VAL(glibcxx_cv_c99_stdio_cxx11, [
      GCC_TRY_COMPILE_OR_LINK(
        [#include <stdio.h>
         #include <stdarg.h>
         void foo(char* fmt, ...)
         {
           va_list args; va_start(args, fmt);
           vfscanf(stderr, "%i", args);
           vscanf("%i", args);
           vsnprintf(fmt, 0, "%i", args);
           vsscanf(fmt, "%i", args);
           snprintf(fmt, 0, "%i");
         }], [],
        [glibcxx_cv_c99_stdio_cxx11=yes], [glibcxx_cv_c99_stdio_cxx11=no])
    ])
    AC_MSG_RESULT($glibcxx_cv_c99_stdio_cxx11)
    if test x"$glibcxx_cv_c99_stdio_cxx11" = x"yes"; then
      AC_DEFINE(_GLIBCXX11_USE_C99_STDIO, 1,
        [Define if C99 functions or macros in <stdio.h> should be imported
        in <cstdio> in namespace std for C++11.])
    fi

    # Check for the existence in <stdlib.h> of lldiv_t, et. al.
    AC_MSG_CHECKING([for ISO C99 support in <stdlib.h> for C++11])
    AC_CACHE_VAL(glibcxx_cv_c99_stdlib_cxx11, [
      GCC_TRY_COMPILE_OR_LINK(
        [#include <stdlib.h>
         volatile float f;
         volatile long double ld;
         volatile unsigned long long ll;
         lldiv_t mydivt;],
        [char* tmp;
         f = strtof("gnu", &tmp);
         ld = strtold("gnu", &tmp);
         ll = strtoll("gnu", &tmp, 10);
         ll = strtoull("gnu", &tmp, 10);
         ll = llabs(10);
         mydivt = lldiv(10,1);
         ll = mydivt.quot;
         ll = mydivt.rem;
         ll = atoll("10");
         _Exit(0);
        ], [glibcxx_cv_c99_stdlib_cxx11=yes], [glibcxx_cv_c99_stdlib_cxx11=no])
    ])
    AC_MSG_RESULT($glibcxx_cv_c99_stdlib_cxx11)
    if test x"$glibcxx_cv_c99_stdlib_cxx11" = x"yes"; then
      AC_DEFINE(_GLIBCXX11_USE_C99_STDLIB, 1,
        [Define if C99 functions or macros in <stdlib.h> should be imported
        in <cstdlib> in namespace std for C++11.])
    fi`

Not sure how best to fix that, though. Maybe it would be best to fix newlib & clib2 instead, so that those tests pass?

**Comment by sba1** [comment]
> Not sure how best to fix that, though. Maybe it would be best to fix newlib & clib2 instead, so that those tests pass?

Yes. See my previous message. But there are workarounds possible, see my other note above.

**Comment by ksdhans** [comment]
> 
> Am 2020-04-14 05:27, schrieb ksdhans:
> @sba1 [1] Thanks. However, the c++config.h files are in a subdirectory of adtools/native-build/gcc-cross-build-8.3.0/. That directory created during the build process, and it looks like c++config.h is generated somehow. I haven't managed to find its source or generator code. Any idea where to find that?
> See the patch 0011-Pretend-C99-compatibility.patch for an example how to fix such issue. The real fix would be to fix newlib of course (and to distribute a fixed version).

Hmm. That patch doesn't seem to work properly with GCC 8, because _GLIBCXX11_USE_C99_STDIO is still undefined (it *is* set for clib2, although both don't have _GLIBCXX11_USE_C99_STDLIB set). So the tests I quoted above still fails.

**Comment by sba1** [comment]
The patch is not meant to make the test non-failing, however, to overwrite the outcome of it. But a similar technique can be implemented to for the other cases. In gcc 8 they made these stuff more fine-tuned.

**Comment by kas1e** [comment]
from newlib's side everything about "not a member of std::" was fixed in the new beta of newlib 53.69 and adtools recompiled with new newlib's headers.

**Comment by kas1e** [comment]
As from the side of clib2 it already works before, and start to works now since the new beta of newlib, we can close this ticket
