### ISSUE TITLE
error: ‘round’ is not a member of ‘std’

### ISSUE THREAD

**Issue by kas1e** [sba1/adtools#59]
Another error about not being member of 'std'. At this time it is "round" function.

There is very basic example:

`#include <iostream>`
`#include <cmath>`

`int main()`
`{`
`            std::cout<<"round(0.5) = "<<std::round(0.5);`
`}`

Via cygwins compiler (7.3.0) it compiles just by "g++ test.cpp".

For os4 i trying to compile it like:

$ ppc-amigaos-g++ -athread=native -std=c++11 test3.cpp

And have:

`test3.cpp: In function ‘int main()’:`
`test3.cpp:6:39: error: ‘round’ is not a member of ‘std’`
`      std::cout<<"round(0.5) = "<<std::round(0.5);`

Adding of -mcrt=clib2 , didn't help as well.

**Comment by sba1** [comment]
Am 2018-11-13 12:42, schrieb kas1e:
> Another error about not being member of 'std'. At this time it is
> "round" function.

Can you perhaps create a patch that adds all those stuff to the tests 
directory?

**Comment by kas1e** [comment]
I not good at creating patches, but i just upload those 3 tests there:
http://kas1e.mikendezign.com/aos4/adtools/tests/

If it will of any help in that way, of course.

**Comment by kas1e** [comment]
As of beta versions of newlib 53.69 main issue and all test cases from this ticket very fixed by recompiling adtools with newlib includes from 53.69
