### ISSUE TITLE
gcc: c++11 functions not used or toolchain (slightly) broken(?)

### ISSUE THREAD

**Issue by raziel-** [sba1/adtools#6]
Compiling ScummVM (and ResidualVM aswell, they share the same code base) project leads to an early error pointing to a missing vsprintf if i usie the projects switch --enable-c++.
(Dropping the switch makes the compiler run without problems)

I'll crosslink to the projects bugreport because i don't really know what is going wrong or what i could do to resolve this or further test:
https://sourceforge.net/p/scummvm/bugs/6988/

If you need specific testing, please let me know

**Comment by sba1** [comment]
Please provide a test example.

**Comment by sba1** [comment]
Okay, tested myself. --std=c++11 enables the __STRICT_ANSI__ macro and for newlib this excludes the vsnprintf() definition. So it is more or less a non-supported featrue of the SDK. 

To workaround the problem use --std=gnu++11 or -U__STRICT_ANSI__ until the SDK has C++11 support.

**Comment by raziel-** [comment]
Thank you very much
