### ISSUE TITLE
installer wrong download SDK 53.24, while latest one are 53.30.

### ISSUE THREAD

**Issue by kas1e** [sba1/adtools#60]
Found lately that miss some defination in new adtools installation, and was curius why, and find out that by some reassons SDK 53.24 are downloaded, and then renamed to 53.30 ! While real 53.30 didn't downloaded. 

There is even pull request with fix:
https://github.com/sba1/adtools/pull/55

So had manually dl 53.30 and update. Not big deal, but probabaly need to be fixed.

**Comment by ksdhans** [comment]
I second updating to the latest SDK. It's been around since 2015, and 53.24 is even older.

**Comment by ksdhans** [comment]
I just checked the native-build makefile, and theres a bug there. SDK_VERSION is set to 53.30, which gives the impression that 53.30 is downloaded. However, the SDK_URL is wrong. It should be:
SDK_URL=http://www.hyperion-entertainment.biz/index.php?option=com_registration&view=download&format=raw&file=82&Itemid=82

**Comment by 3246251196** [comment]
@sba1 
This ticket can be closed.

**Comment by sba1** [comment]
Yes, thanks!
