### ISSUE TITLE
ISI exception

### ISSUE THREAD

**Issue by capehill** [sba1/adtools#7]
I get ISI exception when using libSDL built with GCC5. When application is started, and library constructor called, code jumps somewhere.

Here is a smaller example which has the same issue:

``` C
#include <stdio.h>

void _INIT_thread_init(void) __attribute__((constructor));
void _EXIT_thread_term(void) __attribute__((destructor));


void plistInit(int *param)
{
    if(param)
    {
        *param = 123;
    }
}

void _INIT_thread_init(void)
{
    int i;
    plistInit(&i);

    printf("init\n");
}

void _EXIT_thread_term(void)
{
    printf("exit\n");
}

int main(void)
{
    printf("main\n");
    return 0;
}
```

It needs to be compiled like:

gcc test.c -fPIC -use-dynld

running a.out generates ISI.

**Comment by capehill** [comment]
There was stdio.h included, formatting broke.

**Comment by sba1** [comment]
Can you try different optioins, e.g., without -use-dynld? Also try another clib, e.g., ```mcrt=clib2```. Thanks

**Comment by capehill** [comment]
Smaller example:

#include <stdio.h>

int main(void)
{
	printf("hello\n");
	return 0;
}

If compiled with -fPIC and linked with -use-dynld, it will throw ISI.

**Comment by capehill** [comment]
How to link with clib2? I get undefined reference to GetProgramName.

Binary works if not compiled with -fPIC or linked with -use-dynld, but combination of both seems to crash when printf function is called.

**Comment by sba1** [comment]
If I'm not mistaken tham there is no need for -fPIC for the main executable. Use it only, when generating shared objects. IMO best would be to avoid shared object altogether.

**Comment by capehill** [comment]
Yes, I agree that binary doesn't need to be compiled with -fPIC. That was just the smallest example I could come up with. But it looks like currently it is not possible to build shared objects with GCC5. It looks like function calls from -fPIC compiled code trigger ISI. I have one more example. Let's create a shared object and binary which uses it.

// library.c
int g(int param)
{
	return param;
}

int f(int param)
{
	return g(param);
}

// application.c
#include <stdio.h>

int f(int);

int main(void)
{
	printf( "%d\n", f(123) );
	return 0;
}

gcc -o library.o -c library.c -fPIC
gcc -o liblibrary.so library.o -shared
gcc -o application.o -c application.c
gcc -o application application.o -L. -llibrary -use-dynld

Running application triggers ISI.

**Comment by sba1** [comment]
I'll see what I can do. Shared Objects have been not tested at all (I'm not using them).

**Comment by sba1** [comment]
I've conducted a clean room test now and it seems to work. Can you verify that the shared objects are used with the archive?

**Comment by capehill** [comment]
Yeah, seems to be used. However, there was an original issue that libgcc.so couldn't be found at all. There is a thread at Amigans.net ( http://www.amigans.net/modules/xforum/viewtopic.php?post_id=100407#forumpost100407 ) that shows how to fix it. Could it still be that the supplied libgcc.so has some issues? Filesize of libgcc.so is 479050 bytes.

[Snoopy_Output.txt](https://github.com/sba1/adtools/files/76628/Snoopy_Output.txt)

**Comment by sba1** [comment]
I cannot see which shared object is used when you start the program (i.e., after you compiled it). Can you verify that the correct one is used? Don't know if you can convince Snoopy to make this visible. Perhaps you need to point sobj: to another directory.

**Comment by capehill** [comment]
If I assign SOBJS: RAM:, and copy the new libgcc.so to RAM:, and then compile and run test, it works. So it looks like crash is related to my SOBJS: content somehow.
