### ISSUE TITLE
FR: Support c++11 (or at least some not yet supported functions)

### ISSUE THREAD

**Issue by raziel-** [sba1/adtools#70]
Using the flag --enable-c++11 with configure (ScummVM and ResidualVM) makes the compiler break with an error early on in commandline.cpp.

    C++      base/commandLine.o
base/commandLine.cpp: In function 'void Base::usage(const char*, ...)':
base/commandLine.cpp:191:2: error: 'vsnprintf' was not declared in this scope
  vsnprintf(buf, STRINGBUFLEN, s, va);
  ^~~~~~~~~
base/commandLine.cpp:191:2: note: suggested alternative: 'vsprintf'
  vsnprintf(buf, STRINGBUFLEN, s, va);
  ^~~~~~~~~
  vsprintf
gmake: *** [base/commandLine.o] Error 1

Of course, this only happens with the compiler flag --enable-c++11 in place, if i leave that be everything compiles normal, so i guess our toolchain is still missing something wrt c++11(?)

gcc (adtools build 8.3.0) 8.3.0

Also take a look here: https://bugs.scummvm.org/ticket/6988

**Comment by sba1** [comment]
Am 2019-03-22 20:01, schrieb Hubert Maier:
> Using the flag --enable-c++11 with configure (ScummVM and ResidualVM)
> makes the compiler break with an error early on in commandline.cpp.

vsnprintf is part of clib2, not sure about newlib. Can you try 
-mcrt=clib2?

Bye
Sebastian

**Comment by capehill** [comment]
vsnprintf should be usable in newlib too (didn't try C++11 though).

**Comment by raziel-** [comment]
quote
The Scumm engine uses snprintf and vsnprintf. Newlib does have these
functions, but it hides them when --std=c++11 is specified. It
does this because __STRICT_ANSI__ is being set, but __STDC_VERSION__
is not set to 199901 or higher (because we are compiling C++, not C).
/quote

The problem was, that even if i used --std=gnu++11 it was overruled by configure.
This has been fixed in-tree and will be part of a future update, hence it is not a problem of adtools.

Thank you for the pointer, though.
