### ISSUE TITLE
sorry - this program has been built without plugin support

### ISSUE THREAD

**Issue by chris-y** [sba1/adtools#8]
I'm getting the above error whilst trying to run the makefile for libiconv with gcc 5.3.0

Apparently the fix is to add --enable-plugins to the configure line when building binutils.

I've tried this (for the cross compiler) and it works.  Please can this be added to the makefile in the repo.

```diff
index bea129b..4ff5c32 100644
--- a/binutils-build/Makefile
+++ b/binutils-build/Makefile
@@ -18,6 +18,7 @@ all: cross
 cross:
 	mkdir -p $(CROSS_BUILD_DIR)
 	cd $(CROSS_BUILD_DIR); CFLAGS="-Wno-switch -Wno-unused" $(REAL_SRC_DIR)/configure \
+									--enable-plugins \
 									--target=ppc-amigaos \
 									--prefix=$(PREFIX)
 	make -C $(CROSS_BUILD_DIR)
```

I assume it is needed for the native binutils too, but I've not used that at all so I don't know.

**Comment by jens-maus** [comment]
Best would be if you would file a pull request with git. Then integrating your proposed change is a matter of one mouse click.

**Comment by sba1** [comment]
Am 2016-01-03 14:18, schrieb Jens Maus:
> Best would be if you would file a pull request with git. Then
> integrating your proposed change is a matter of one mouse click.

I'm not sure if plugins support works in a native environment, so this 
has to be verified before.

What kind of plugins does iconv need?

**Comment by chris-y** [comment]
No idea, it didn't look like it was doing anything special.
